packages:
  - 'apps/*'
  - 'packages/*'
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
overrides:
  vite: ^8.2.2
  tmp: ^0.2.6
  '@nestjs/cli>glob': ^10.5.0
  '@angular-devkit/core>picomatch': ^4.0.4
