packages:
  - 'apps/*'
  - 'packages/*'
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
overrides:
  vite: ^6.4.3
  tmp: ^0.2.6
