{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "okvns.namespace" . }}
  labels:
    app.kubernetes.io/part-of: {{ include "okvns.partOf" . }}
{{- end }}
